# import

In [1]:
import numpy as np

- numpy의 호출 방법

- 일반적으로 numpy는 np라는 alias(별칭)를 이용해서 호출함

- 특별한 이유는 없음 세계적인 약속 같은 것

# Array creation

In [2]:
test_array = np.array([1,4,5,8], float)
print(test_array)
type(test_array[3])

[1. 4. 5. 8.]


numpy.float64

- numpy는 np.array 함수를 활용하여 배열을 생성함 -> ndarray

- numpy는 하나의 데이터 type만 배열에 넣을 수 있음

- List와 가장 큰 차이점, Dynamic typing not supported

- C의 Array를 사용하여 배열을 생성함

In [3]:
test_array = np.array([1,4,5,'8'], float) # String Type의 데이터를 입력해도
print(test_array)
print(type(test_array[3])) # Float Type으로 자동 형변환을 실시
print(test_array.dtype) # Array(배열) 전체의 데이터 Type을 반환함
print(test_array.shape) # Array(배열) 의 shape을 반환함

[1. 4. 5. 8.]
<class 'numpy.float64'>
float64
(4,)


- shape: numpy array의 object의 dimension 구성을 반환함

- dtype: numpy array의 데이터 type을 반환함

# Array shape(vector)

- Array (vector, matrix, tensor)의 크기, 형태 등에 대한 정보

In [4]:
test_array = np.array([1, 4, 5, '8'], float)
test_array

array([1., 4., 5., 8.])

# Array shape(matrix)

In [5]:
matrix = [[1,2,5,8], [1,2,5,8], [1,2,5,8]]
np.array(matrix, int).shape

(3, 4)

# Array shape(3rd order tensor)

In [7]:
tensor = [[[1,2,5,8], [1,2,5,8], [1,2,5,8]],
         [[1,2,5,8], [1,2,5,8], [1,2,5,8]],
         [[1,2,5,8], [1,2,5,8], [1,2,5,8]],
         [[1,2,5,8], [1,2,5,8], [1,2,5,8]]]
np.array(tensor, int).shape

(4, 3, 4)

# Array shape - ndim & size

- ndim - number of dimension

- size - data의 개수

In [8]:
np.array(tensor, int).ndim

3

In [9]:
np.array(tensor, int).size

48

# Array dtype

- Ndarray의 singlr element가 가지는 data type

- 각 element가 차지하는 memory의 크기가 결정됨

In [11]:
np.array([[1,2,3], [4.5, 5, 6]], dtype=int)

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
np.array([[1,2,3], [4.5, '5', '6']], dtype=np.float32)

array([[1. , 2. , 3. ],
       [4.5, 5. , 6. ]], dtype=float32)

# Array dtype

- nbytes - ndarray object의 메모리 크기를 반환함

In [13]:
np.array([[1,2,3], [4.5, '5', '6']], dtype=np.float32).nbytes
# 32bits = 4bytes -> 6*4bytes

24

In [14]:
np.array([[1,2,3], [4.5, '5', '6']], dtype=np.int8).nbytes
# 8bits = 1bytes -> 6*1bytes

6

In [15]:
np.array([[1,2,3], [4.5, '5', '6']], dtype=np.float64).nbytes
# 64bits = 8bytes -> 6*8ytes

48

# reshape

- Array의 shape의 크기를 변경함 (element의 갯수는 동일)

In [16]:
test_matrix = [[1,2,3,4], [1,2,5,8]]
np.array(test_matrix).shape

(2, 4)

In [17]:
np.array(test_matrix).reshape(8,)

array([1, 2, 3, 4, 1, 2, 5, 8])

In [19]:
np.array(test_matrix).reshape(8,).shape

(8,)

- Array의 size만 같다면 다차원으로 자유로이 변형가능

In [20]:
np.array(test_matrix).reshape(2,4).shape

(2, 4)

In [22]:
np.array(test_matrix).reshape(-1,2).shape
# -1: size를 기반으로 row 개수 선정

(4, 2)

In [23]:
np.array(test_matrix).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [24]:
np.array(test_matrix).reshape(2,2,2).shape

(2, 2, 2)

# flatten

- 다차원 array를 1차원 array로 변환

In [25]:
test_matrix = [[1,2,3,4], [1,2,5,8], [1,2,5,8], [1,2,5,8], [1,2,5,8]]
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 1, 2, 5, 8, 1, 2, 5, 8, 1, 2, 5, 8, 1, 2, 5, 8])

# indexing

- List와 달리 이차원 배열에서 [0,0]과 같은 표기법을 제공함

- Matrix일 경우 앞은 row 뒤는 column을 의미함

In [26]:
a = np.array([[1,2,3], [4.5, 5,6]], int)
print(a)
print(a[0,0]) # Two dimensional array representation #1
print(a[0][0]) # Two dimensional array representation #2

a[0,0] = 12 # Matrix 0,0에 12 할당
print(a)
a[0][0] = 5 # Matrix 0,0에 12 할당
print(a)

[[1 2 3]
 [4 5 6]]
1
1
[[12  2  3]
 [ 4  5  6]]
[[5 2 3]
 [4 5 6]]


# slicing

- List와 달리 행과 열 부분을 나눠서 slicing이 가능함

- Matrix의 부분 집합을 추출할 때 유용함

In [27]:
a = np.array([[1,2,3,4,5],
             [6,7,8,9,10]], int)
a[:,2:] # 전체 Row의 2열 이상
a[1,1:3] # 1 Row의 1열 ~ 2열
a[1:3] # 1 Row ~ 2 Row의 전체

array([[ 6,  7,  8,  9, 10]])

# arange

- array의 범위를 지정하여, 값의 list를 생성하는 명령어

In [28]:
np.arange(30) # range: List의 range와 같은 효과, integer로 0부터 29까지 배열 추출

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [29]:
np.arange(0, 5, 0.5) # floating point도 표시 가능함

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [30]:
np.arange(30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

# ones, zeros and empty

- zeros - 0으로 가득찬 ndarray 생성

In [31]:
np.zeros(shape=(10,), dtype=np.int8) # 10 - zero vector 생성

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [32]:
np.zeros((2,5)) # 2 by 5 - zero matrix 생성

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

- ones - 1로 가득찬 ndarray 생성

In [33]:
np.ones(shape=(10,), dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [34]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

- empty - shape만 주어지고 비어 있는 ndarray 생성

(memory initialization 이 되지 않음)

In [35]:
np.empty(shape=(10,), dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [36]:
np.empty((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# something_like

- 기존 ndarray의 shape 크기 만큼 1, 0 또는 empty array를 반환

In [37]:
test_matrix = np.arange(30).reshape(5,6)
np.ones_like(test_matrix)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

# identity

- 단위 행렬(i 행렬)을 생성함

In [38]:
np.identity(n=3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [39]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# eye

- 대각선이 1인 행렬, k값의 시작 index의 변경이 가능

In [40]:
np.eye(N=3, M=5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [41]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
np.eye(3,5,k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# diag

- 대각 행렬의 값을 추출함

In [46]:
matrix = np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [47]:
np.diag(matrix)

array([0, 4, 8])

In [48]:
np.diag(matrix, k=1)

array([1, 5])

# random sampling

- 데이터 분포에 따른 sampling으로 array를 생성

In [49]:
np.random.uniform(0,1,10).reshape(2,5) # 균등분포

array([[0.92799603, 0.55550392, 0.78940974, 0.78881918, 0.31432995],
       [0.37796488, 0.46526536, 0.2853065 , 0.74267275, 0.25808673]])

In [50]:
np.random.normal(0,1,10).reshape(2,5) # 정규분포

array([[ 0.41809599,  1.34660465, -0.67190937,  1.36654447, -0.78127641],
       [ 0.31519302,  0.35362442, -0.16403085, -0.95947526, -0.51143608]])

# concatenate

- Numpy array를 합치는 함수

In [51]:
a = np.array([1,2,3])
b = np.array([2,3,4])
np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

In [52]:
a = np.array([[1],[2],[3]])
b = np.array([[2],[3],[4]])
np.hstack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])

In [53]:
a = np.array([[1,2,3]])
b = np.array([[2,3,4]])
np.concatenate((a,b), axis=0)

array([[1, 2, 3],
       [2, 3, 4]])

In [54]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
np.concatenate((a,b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

# All & Any

- Array의 데이터 전부(and) 또는 일부(or)가 조건에 만족 여부 반환

In [55]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
np.any(a>5), np.any(a<0) # any -> 하나라도 조건에 만족한다면 true

(True, False)

In [58]:
np.all(a>5), np.all(a<10) # all -> 모두가 조건에 만족한다면 true

(False, True)

# np.where

In [59]:
np.where(a > 0, 3, 2) # where(condition, TRUE, FALSE)

array([2, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [60]:
a = np.arange(10)
np.where(a>5)

(array([6, 7, 8, 9], dtype=int64),)

In [61]:
a = np.array([1, np.NaN, np.Inf], float)
np.isnan(a)

array([False,  True, False])

In [62]:
np.isfinite(a)

array([ True, False, False])

# Pandas

- 구조화된 데이터의 처리를 지원하는 Python 라이브러리

- 고성능 Array 계산 라이브러리인 Numpy와 통합하여, 강력한 '스프레드시트'처리 기능을 제공

- 인덱싱, 연산용 함수, 전처리 함수 등을 제공함

# 신뢰성 때 했던거라 또 치기 귀찮다..